dbg

diff --git a/templates/nodegroupconfiguration-drbd-install-debian-like.yaml b/templates/nodegroupconfiguration-drbd-install-debian-like.yaml
--- a/templates/nodegroupconfiguration-drbd-install-debian-like.yaml
+++ b/templates/nodegroupconfiguration-drbd-install-debian-like.yaml
@@ -175,6 +175,19 @@ spec:
     DRBD_BUILD_SERVER_URL="http://${DRBD_BUILD_SERVER_IP}:2021"
     bb-log-info "DRBD build server url: $DRBD_BUILD_SERVER_URL"
 
+    attempt=0
+    until [[ "$(d8-curl -ks -w '%{http_code}' -o /dev/null $DRBD_BUILD_SERVER_URL'/api/v1/hello')" == "200" ]]
+    do
+      if [ $attempt -gt 3 ]; then
+        bb-log-info "DRBD_BUILD_SERVER_URL service isn't accessible, can't continue DRBD building"
+        exit 1
+      fi
+
+      ((attempt=attempt+1))
+      bb-log-info "Waiting for DRBD_BUILD_SERVER_URL service is being accessible (try #$attempt)"
+      sleep 10
+    done
+
     KERNEL_VERSION=$kernel_version_in_use
     KERNEL_VERSION_SHORT="${KERNEL_VERSION%-generic}"
     bb-log-info "Detected kernel version: $KERNEL_VERSION"
