* first stork patch (just print custom log line on startup)
Signed-off-by: Ivan.Makeev <ivan.makeev@flant.com>

diff --git a/images/linstor-scheduler-extender/Dockerfile b/images/linstor-scheduler-extender/Dockerfile
--- a/images/linstor-scheduler-extender/Dockerfile
+++ b/images/linstor-scheduler-extender/Dockerfile
@@ -4,14 +4,26 @@ ARG BASE_GOLANG_BULLSEYE=registry.deckhouse.io/base_images/golang:1.22.6-bullsey
 FROM $BASE_GOLANG_BULLSEYE as builder
 ARG LINSTOR_SCHEDULER_EXTENDER_GITREPO=https://github.com/piraeusdatastore/linstor-scheduler-extender
 ARG LINSTOR_SCHEDULER_EXTENDER_VERSION=0.3.2
+ARG STORK_GITREPO=https://github.com/libopenstorage/stork
+# the closest version I found for the stork's module version v1.4.1-0.20220512171133-b99428ee1ddf which used in linstor-scheduler-extender v0.3.2
+# https://github.com/libopenstorage/stork/pull/1097/commits
+ARG STORK_VERSION=v2.11.5
 
 # Copy patches
 COPY ./patches /patches
+
+# Stork patching
+RUN git clone ${STORK_GITREPO} /usr/local/go/stork \
+ && cd /usr/local/go/stork \
+ && git reset --hard ${STORK_VERSION} \
+ && [ -n "$(ls -A /patches/stork/*.patch 2>/dev/null)" ] && git apply /patches/stork/*.patch || echo "Stork patches not found. Git patching skipped"
 
 RUN git clone ${LINSTOR_SCHEDULER_EXTENDER_GITREPO} /usr/local/go/linstor-scheduler-extender \
  && cd /usr/local/go/linstor-scheduler-extender \
  && git reset --hard v${LINSTOR_SCHEDULER_EXTENDER_VERSION} \
  && [ -n "$(ls -A /patches/*.patch 2>/dev/null)" ] && git apply /patches/*.patch || echo "Patches not found. Git patching skipped" \
+ && go mod edit -replace=github.com/libopenstorage/stork=/usr/local/go/stork \
+ && go mod tidy \
  && cd cmd/linstor-scheduler-extender \
  && go build -ldflags="-X github.com/piraeusdatastore/linstor-scheduler-extender/pkg/consts.Version=v${LINSTOR_SCHEDULER_EXTENDER_VERSION}" \
  && mv ./linstor-scheduler-extender /
